version: "3.8"

# 컴퓨터들
services:
  # 컴퓨터이름
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/app/src
    ports:
      - 3000:3000
    env_file:
      - ./.env

  # 컴퓨터이름
  my-database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  my-redis:
    image: redis:latest
    ports:
      - 6379:6379

